# Total Marks: 100
### Each question 10 marks
**Question 1: -**
Write a program that takes a string as input, and counts the frequency of each word in the string, there might be repeated characters in the string. Your task is to find the highest frequency and returns the length of the highest-frequency word.

**Note -** You have to write at least 2 additional test cases in which your program will run successfully and provide an explanation for the same.

**Example input -** string = “write write write all the number from from from 1 to 100”

**Example output -** 5

**Explanation -** From the given string we can note that the most frequent words are “write” and “from” and the maximum value of both the values is “write” and its corresponding length is 5

In [1]:
def find_highest_frequency_word_length(string):
    words = string.split()

    word_freq = {}

    for word in words:
        word_freq[word] = word_freq.get(word, 0) + 1

    max_freq = 0
    max_length = 0
    for word, freq in word_freq.items():
        if freq > max_freq or (freq == max_freq and len(word) > max_length):
            max_freq = freq
            max_length = len(word)

    return max_length

In [2]:
#Example test case

string = "write write write all the number from from from 1 to 100"
result = find_highest_frequency_word_length(string)
print(result)

#In the given example, the word "write" appears three times, making it the most frequent word. Its length is 5 characters, so the program returns 5.

5

In [3]:
# Test case with a single word repeated multiple times:

string = "hello hello hello hello hello"
result = find_highest_frequency_word_length(string)
print(result)
# In this case, the word "hello" appears five times, which is the highest frequency. Its length is 5 characters, so the program returns 5.

5

In [4]:
# Test case with different words having the same frequency:


string = "apple orange banana apple orange banana apple orange banana"
result = find_highest_frequency_word_length(string)
print(result)

#In this case, the words "apple," "orange," and "banana" appear three times each, making their frequency the highest. Among these words, "banana" has the longest length of 6 characters, so the program returns 6.

6

**Question 2: -**
    
Consider a string to be valid if all characters of the string appear the same number of times. It is also valid if he can remove just one character at the index in the string, and the remaining characters will occur the same number of times. Given a string, determine if it is valid. If so, return YES , otherwise return NO.

**Note -** You have to write at least 2 additional test cases in which your program will run successfully and provide an explanation for the same.

**Example input 1 -** s = “abc”. This is a valid string because frequencies are { “a”: 1, “b”: 1, “c”: 1 }

**Example output 1-** YES

**Example input 2 -** s “abcc”. This string is not valid as we can remove only 1 occurrence of “c”. That leaves character frequencies of { “a”: 1, “b”: 1 , “c”: 2 }

**Example output 2 -** NO

In [5]:
def is_valid(s):
    freq = {}
    for char in s:
        if char in freq:
            freq[char] += 1
        else:
            freq[char] = 1
    values = list(freq.values())
    values.sort()
    unique_values = set(values)
    
    if len(unique_values) == 1:
        return "YES"
    elif len(unique_values) == 2:
        if values.count(values[0]) == 1 and values[0] == 1:
            return "YES"
        elif values.count(values[-1]) == 1 and values[-2] == values[-1] - 1:
            return "NO"  
    
    return "NO"

In [6]:
# Example input 1
s = "abc"
print(is_valid(s))  
# Explaination: This is a valid string because frequencies are { “a”: 1, “b”: 1, “c”: 1 }

YES

In [7]:
# Example input 2
s = "abcc"
print(is_valid(s))  
# Explaination: This string is not valid as we can remove only 1 occurrence of “c”. That leaves character frequencies of { “a”: 1, “b”: 1 , “c”: 2 }

NO

In [8]:
# input 3
s = "aabbbcc"
print(is_valid(s))  
# Explaination: In this case, the string "aabbbcc" has three distinct characters: 'a', 'b', and 'c'. The frequencies of these characters are [2, 3, 2], which are not all equal and cannot be rearranged to form a valid string. No matter how we rearrange the characters, we cannot make the frequencies equal. Therefore, the output is "NO".

NO

In [9]:
# input 4
s = "aabbcc"
print(is_valid(s))  
# Explaination: In this case, the string "aabbcc" has three distinct characters: 'a', 'b', and 'c'. The frequencies of these characters are [2, 2, 2], which are all equal. Therefore, the output is "YES" since the string is already valid.

YES

**Question 3: -**

Write a program, which would download the data from the provided link, and then read the data and convert that into properly structured data and return it in Excel format.
**Note -** Write comments wherever necessary explaining the code written.

**Link -** https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json

**Data Attributes - id:** Identification Number - int num: Number of the

● Pokémon in the official Pokédex - int name: Pokémon name -

● string img: URL to an image of this Pokémon - string type:

● Pokémon type -string height: Pokémon height - float

● weight: Pokémon weight - float candy: type of candy used to evolve Pokémon or given

● when transferred - string candy_count: the amount of candies required to evolve
- int

● egg: Number of kilometers to travel to hatch the egg - float spawn_chance:

● Percentage of spawn chance (NEW) - float avg_spawns: Number of this
pokemon on 10.000 spawns (NEW) - int

● spawn_time: Spawns most active at the time on this field. Spawn times are the same for all
time zones and are expressed in local time. (NEW) - “minutes: seconds” multipliers:
Multiplier of Combat Power (CP) for calculating the CP after evolution See below - list of int
weakness: Types of

● Pokémon this Pokémon is weak to - list of strings next_evolution: Number and Name of
successive evolutions of Pokémon - list of dict prev_evolution: Number and Name of previous
evolutions of Pokémon - - list of dict

In [49]:
import requests
import pandas as pd

# Retrieve the raw JSON data

def json_to_csv(link):
    response = requests.get(link)
    data = response.json()["pokemon"]

    # Convert JSON data to DataFrame
    df = pd.DataFrame(data)
    
    df.to_csv("Output.csv", index=False)

In [50]:
link = "https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json"
json_to_csv(link)

In [51]:
df1 = pd.read_csv("Output.csv")
df1.to_excel("Output.xlsx")

In [52]:
df1

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","['Ice', 'Dragon', 'Fairy']","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"['Ice', 'Dragon', 'Fairy']","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"['Ice', 'Rock', 'Dragon', 'Fairy']",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN

In [53]:
df1.dtypes

id                  int64
num                 int64
name               object
img                object
type               object
height             object
weight             object
candy              object
candy_count       float64
egg                object
spawn_chance      float64
avg_spawns        float64
spawn_time         object
multipliers        object
weaknesses         object
next_evolution     object
prev_evolution     object
dtype: object

**Question 4 -**

Write a program to download the data from the link given below and then read the data and convert the into the proper structure and return it as a CSV file.

**Link -** https://data.nasa.gov/resource/y77d-th95.json

**Note -** Write code comments wherever needed for code understanding

Excepted Output Data Attributes

● Name of Earth Meteorite - string id - ID of Earth

● Meteorite - int nametype - string recclass - string

● mass - Mass of Earth Meteorite - float year - Year at which Earth

● Meteorite was hit - datetime format reclat - float recclong - float

● point coordinates - list of int

In [32]:
import requests
import json
import csv

def download_data(url):
    response = requests.get(url)
    data = response.json()
    return data

def convert_to_csv(data, filename):
    # Extracting the expected output data attributes from the JSON data
    attributes = [
        "name",
        "id",
        "nametype",
        "recclass",
        "mass",
        "year",
        "reclat",
        "reclong",
        "geolocation.coordinates"
    ]

    # Opening the CSV file and writing the header
    with open(filename, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(attributes)

        # Writing each record as a row in the CSV file
        for item in data:
            row = []
            for attribute in attributes:
                # Handling nested attributes
                if '.' in attribute:
                    nested_attributes = attribute.split('.')
                    nested_value = item.get(nested_attributes[0], {})
                    for nested_attribute in nested_attributes[1:]:
                        nested_value = nested_value.get(nested_attribute, '')
                    row.append(nested_value)
                else:
                    row.append(item.get(attribute, ''))
            writer.writerow(row)

    print("CSV file generated successfully.")

# URL of the JSON data
url = "https://data.nasa.gov/resource/y77d-th95.json"

# Download the data from the URL
data = download_data(url)

# Convert and save the data as a CSV file
convert_to_csv(data, "Output.csv")

UnicodeEncodeError: 'charmap' codec can't encode character '\u0141' in position 0: character maps to <undefined>

**Question 5 -**

Write a program to download the data from the given API link and then extract the following data with
proper formatting

Link - http://api.tvmaze.com/singlesearch/shows?q=westworld&embed=episodes

Note - Write proper code comments wherever needed for the code understanding

Excepted Output Data Attributes -

● id - int url - string

● name - string season

● - int number - int

● type - string airdate -

● date format airtime -

● 12-hour time format

● runtime - float

● average rating - float

● summary - string

● without html tags

● medium image link - string

● Original image link - string

In [33]:
import requests
import json
from bs4 import BeautifulSoup

In [34]:
# API URL
url = "http://api.tvmaze.com/singlesearch/shows?q=westworld&embed=episodes"

In [35]:
# Send a GET request to the API URL and retrieve the data
response = requests.get(url)
data = json.loads(response.text)

In [41]:
# Iterate over each episode and extract the required data
for episode in data['_embedded']['episodes']:
    # Extract attributes
    episode_id = episode['id']
    episode_url = episode['url']
    episode_name = episode['name']
    season = episode['season']
    episode_number = episode['number']
    episode_type = episode['type']
    airdate = episode['airdate']
    airtime = episode['airtime']
    runtime = episode['runtime']
    average_rating = episode['rating']['average']
    
    # Clean up the summary by removing HTML tags using BeautifulSoup
    summary = BeautifulSoup(episode['summary'], 'html.parser').get_text(strip=True)
    
    # Extract image links
    image_medium = episode['image']['medium']
    image_original = episode['image']['original']
    
    # Print the extracted data with proper formatting
    print("Episode ID:", episode_id)
    print("URL:", episode_url)
    print("Name:", episode_name)
    print("Season:", season)
    print("Number:", episode_number)
    print("Type:", episode_type)
    print("Airdate:", airdate)
    print("Airtime:", airtime)
    print("Runtime:", runtime)
    print("Average Rating:", average_rating)
    print("Summary:", summary)
    print("Medium Image Link:", image_medium)
    print("Original Image Link:", image_original)
    print()

Episode ID: 869671
URL: https://www.tvmaze.com/episodes/869671/westworld-1x01-the-original
Name: The Original
Season: 1
Number: 1
Type: regular
Airdate: 2016-10-02
Airtime: 21:00
Runtime: 68
Average Rating: 8
Summary: A woman named Dolores is a free spirit in the Old West... and unaware that she's actually an android, programmed to entertain rich guests seeking to act out their fantasies in an idealized vision of the 1880s. However, the people in charge soon realize that their androids are acting in ways that they didn't anticipate.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/78/195475.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/78/195475.jpg

Episode ID: 911201
URL: https://www.tvmaze.com/episodes/911201/westworld-1x02-chestnut
Name: Chestnut
Season: 1
Number: 2
Type: regular
Airdate: 2016-10-09
Airtime: 21:00
Runtime: 60
Average Rating: 7.7
Summary: Bernard suspects that someone is sabotaging the hosts. Meanwhile, the Man continues his search for the deeper game, and Maeve finds herself in a world of hurt... literally.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/78/195436.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/78/195436.jpg

Episode ID: 911204
URL: https://www.tvmaze.com/episodes/911204/westworld-1x03-the-stray
Name: The Stray
Season: 1
Number: 3
Type: regular
Airdate: 2016-10-16
Airtime: 21:00
Runtime: 60
Average Rating: 7.6
Summary: Bernard continues to investigate Dolores' supposed malfunction, and realizes that he has something unexpected on his hands. Meanwhile, Robert talks about the early days of the park, and Teddy receives a new role and narrative.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/79/198183.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/79/198183.jpg

Episode ID: 911205
URL: https://www.tvmaze.com/episodes/911205/westworld-1x04-dissonance-theory
Name: Dissonance Theory
Season: 1
Number: 4
Type: regular
Airdate: 2016-10-23
Airtime: 21:00
Runtime: 60
Average Rating: 7.9
Summary: While Dolores joins William and Logan on their adventure, the Man in Black continues his search for the entrance to the Maze and meets Armistice. Meanwhile, Robert reveals some of his true power to Theresa and advises her to stay out of his way.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/80/201367.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/80/201367.jpg

Episode ID: 927174
URL: https://www.tvmaze.com/episodes/927174/westworld-1x05-contrapasso
Name: Contrapasso
Season: 1
Number: 5
Type: regular
Airdate: 2016-10-30
Airtime: 21:00
Runtime: 60
Average Rating: 8
Summary: Dolores takes the first step on her path of discovery by deciding to write a new story for herself... where she isn't the damsel. Meanwhile, Elise discovers the Woodcutter's secret, and Robert pays the Man a visit.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/81/204265.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/81/204265.jpg

Episode ID: 932057
URL: https://www.tvmaze.com/episodes/932057/westworld-1x06-the-adversary
Name: The Adversary
Season: 1
Number: 6
Type: regular
Airdate: 2016-11-06
Airtime: 21:00
Runtime: 60
Average Rating: 8
Summary: While Maeve convinces Felix to show her "upstairs," Teddy and the Man close in on the maze. Meanwhile, Bernard and Elsie close in on the identity of the person who is stealing secrets from the park, while Lee meets with a Delos executive director.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/82/207324.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/82/207324.jpg

Episode ID: 938404
URL: https://www.tvmaze.com/episodes/938404/westworld-1x07-trompe-loeil
Name: Trompe L'Oeil
Season: 1
Number: 7
Type: regular
Airdate: 2016-11-13
Airtime: 21:00
Runtime: 60
Average Rating: 8.6
Summary: While William and Dolores travel to the unclaimed territories, Charlotte and Theresa make plans to force Robert out of the park using Clementine. Meanwhile, Maeve continues her plans to escape Westworld.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/83/209400.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/83/209400.jpg

Episode ID: 943065
URL: https://www.tvmaze.com/episodes/943065/westworld-1x08-trace-decay
Name: Trace Decay
Season: 1
Number: 8
Type: regular
Airdate: 2016-11-20
Airtime: 21:00
Runtime: 60
Average Rating: 7.9
Summary: Bernard tries to cope with what he did under Robert's orders. Meanwhile, William and Dolores find a town, and Maeve remembers more of her past. Meanwhile, the Man reveals his past to Teddy.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/84/211554.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/84/211554.jpg

Episode ID: 943066
URL: https://www.tvmaze.com/episodes/943066/westworld-1x09-the-well-tempered-clavier
Name: The Well-Tempered Clavier
Season: 1
Number: 9
Type: regular
Airdate: 2016-11-27
Airtime: 21:00
Runtime: 60
Average Rating: 8.5
Summary: Bernard forces Robert to take him back into his own memories, while the Man meets with Charlotte. Meanwhile, Dolores escapes the Confederado camp and William gives Logan new orders.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/85/213932.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/85/213932.jpg

Episode ID: 943067
URL: https://www.tvmaze.com/episodes/943067/westworld-1x10-the-bicameral-mind
Name: The Bicameral Mind
Season: 1
Number: 10
Type: regular
Airdate: 2016-12-04
Airtime: 21:00
Runtime: 90
Average Rating: 8.7
Summary: Delores finds out the truth about William's fate. Meanwhile, Maeve organizes an escape plan, only to discover that someone else is pulling the strings. And Robert plays the final piece in his grand narrative.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/86/216453.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/86/216453.jpg

Episode ID: 1214222
URL: https://www.tvmaze.com/episodes/1214222/westworld-2x01-journey-into-night
Name: Journey Into Night
Season: 2
Number: 1
Type: regular
Airdate: 2018-04-22
Airtime: 21:00
Runtime: 74
Average Rating: 7.8
Summary: In the aftermath of the host rebellion, the rescue team finds Bernard and the new Head of Operations asks for his help. Meanwhile, Delores promises to show Teddy the truth, and Maeve convinces Lee and Hector to help her find her daughter.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/152/381118.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/152/381118.jpg

Episode ID: 1440915
URL: https://www.tvmaze.com/episodes/1440915/westworld-2x02-reunion
Name: Reunion
Season: 2
Number: 2
Type: regular
Airdate: 2018-04-29
Airtime: 21:00
Runtime: 60
Average Rating: 7.7
Summary: Dolores looks for allies sympathetic to her cause and shows Teddy the truth of his existence. In the past, Dolores gets her first taste of the outside world and William shows her a weapon of mass destruction.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/153/382957.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/153/382957.jpg

Episode ID: 1440916
URL: https://www.tvmaze.com/episodes/1440916/westworld-2x03-virtu-e-fortuna
Name: Virtù e Fortuna
Season: 2
Number: 3
Type: regular
Airdate: 2018-05-06
Airtime: 21:00
Runtime: 60
Average Rating: 7.7
Summary: While Delores makes a deal with the Confederados, Maeve and her group find Felix and Sylvester. Meanwhile, a new Guest comes to Westworld, and Bernard has a meeting of minds with Peter.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/154/386069.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/154/386069.jpg

Episode ID: 1440917
URL: https://www.tvmaze.com/episodes/1440917/westworld-2x04-the-riddle-of-the-sphinx
Name: The Riddle of the Sphinx
Season: 2
Number: 4
Type: regular
Airdate: 2018-05-13
Airtime: 21:00
Runtime: 71
Average Rating: 8
Summary: William pays his recuperating father-in-law several visits. Meanwhile, the Man continues to play Robert's game, and Bernard remembers some of his missing time.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/155/387630.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/155/387630.jpg

Episode ID: 1446362
URL: https://www.tvmaze.com/episodes/1446362/westworld-2x05-akane-no-mai
Name: Akane No Mai
Season: 2
Number: 5
Type: regular
Airdate: 2018-05-20
Airtime: 21:00
Runtime: 60
Average Rating: 7.6
Summary: While Maeve and her people explore Shogun World, Delores realizes that the Teddy she knows can't be a part of the new world coming.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/155/389365.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/155/389365.jpg

Episode ID: 1453278
URL: https://www.tvmaze.com/episodes/1453278/westworld-2x06-phase-space
Name: Phase Space
Season: 2
Number: 6
Type: regular
Airdate: 2018-05-27
Airtime: 21:00
Runtime: 60
Average Rating: 7.7
Summary: Maeve finds her daughter, Delores finds the "real" Teddy, Grace finds her father, and Charlotte and Stubbs find Peter.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/156/390990.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/156/390990.jpg

Episode ID: 1459961
URL: https://www.tvmaze.com/episodes/1459961/westworld-2x07-les-ecorches
Name: Les Écorchés
Season: 2
Number: 7
Type: regular
Airdate: 2018-06-03
Airtime: 21:00
Runtime: 60
Average Rating: 7.9
Summary: Charlotte and Bernard review Bernard's memories to discover what happened to the missing control unit. Meanwhile, Robert has a chat with Bernard, and Maeve confronts her former tormentor.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/156/392143.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/156/392143.jpg

Episode ID: 1459788
URL: https://www.tvmaze.com/episodes/1459788/westworld-2x08-kiksuya
Name: Kiksuya
Season: 2
Number: 8
Type: regular
Airdate: 2018-06-10
Airtime: 21:00
Runtime: 60
Average Rating: 8.7
Summary: Another of Westworld's Host revolutionaries is revealed. Meanwhile, Emily finds the Man and convinces the Ghost Nation to hand him over to her to ensure his suffering.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/157/393811.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/157/393811.jpg

Episode ID: 1459789
URL: https://www.tvmaze.com/episodes/1459789/westworld-2x09-vanishing-point
Name: Vanishing Point
Season: 2
Number: 9
Type: regular
Airdate: 2018-06-17
Airtime: 21:00
Runtime: 60
Average Rating: 8.4
Summary: The Man learns that his grip on reality isn't what he thought, as he considers how his wife died. Meanwhile, Dolores continues her trek across the park to the Valley Beyond, and Bernard receives another visit from Robert.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/158/395754.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/158/395754.jpg

Episode ID: 1459790
URL: https://www.tvmaze.com/episodes/1459790/westworld-2x10-the-passenger
Name: The Passenger
Season: 2
Number: 10
Type: regular
Airdate: 2018-06-24
Airtime: 21:00
Runtime: 90
Average Rating: 8.5
Summary: The Man faces a personal reckoning, while Akecheta and the others find the door. Meanwhile, Bernard meets with Robert one last time after choosing how to deal with Dolores.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/158/397018.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/158/397018.jpg

Episode ID: 1789333
URL: https://www.tvmaze.com/episodes/1789333/westworld-3x01-parce-domine
Name: Parce Domine
Season: 3
Number: 1
Type: regular
Airdate: 2020-03-15
Airtime: 21:00
Runtime: 70
Average Rating: 8
Summary: If you're stuck in a loop, try walking in a straight line.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/246/615760.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/246/615760.jpg

Episode ID: 1800146
URL: https://www.tvmaze.com/episodes/1800146/westworld-3x02-the-winter-line
Name: The Winter Line
Season: 3
Number: 2
Type: regular
Airdate: 2020-03-22
Airtime: 21:00
Runtime: 60
Average Rating: 7.8
Summary: People put up a lot of walls. Bring a sledgehammer to your life.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/247/619379.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/247/619379.jpg

Episode ID: 1800147
URL: https://www.tvmaze.com/episodes/1800147/westworld-3x03-the-absence-of-field
Name: The Absence of Field
Season: 3
Number: 3
Type: regular
Airdate: 2020-03-29
Airtime: 21:00
Runtime: 60
Average Rating: 7.8
Summary: If you don't like what you see in the mirror, don't blame the mirror.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/247/619381.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/247/619381.jpg

Episode ID: 1800148
URL: https://www.tvmaze.com/episodes/1800148/westworld-3x04-the-mother-of-exiles
Name: The Mother of Exiles
Season: 3
Number: 4
Type: regular
Airdate: 2020-04-05
Airtime: 21:00
Runtime: 70
Average Rating: 8
Summary: The truth doesn't always set you free.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/249/623071.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/249/623071.jpg

Episode ID: 1800149
URL: https://www.tvmaze.com/episodes/1800149/westworld-3x05-genre
Name: Genre
Season: 3
Number: 5
Type: regular
Airdate: 2020-04-12
Airtime: 21:00
Runtime: 60
Average Rating: 7.9
Summary: Just say no.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/251/629355.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/251/629355.jpg

Episode ID: 1829375
URL: https://www.tvmaze.com/episodes/1829375/westworld-3x06-decoherence
Name: Decoherence
Season: 3
Number: 6
Type: regular
Airdate: 2020-04-19
Airtime: 21:00
Runtime: 60
Average Rating: 7.5
Summary: Do a lot of people tell you that you need therapy?
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/252/632212.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/252/632212.jpg

Episode ID: 1800151
URL: https://www.tvmaze.com/episodes/1800151/westworld-3x07-passed-pawn
Name: Passed Pawn
Season: 3
Number: 7
Type: regular
Airdate: 2020-04-26
Airtime: 21:00
Runtime: 60
Average Rating: 7.5
Summary: A real friend is one who walks in when the rest of the world walks out. Caleb gets an insight on the true nature of his past; Dolores seeks out Rehoboam's predecessor, while Maeve tracks her down; Bernard, Stubbs, and William escape from all the chaos.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/254/635599.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/254/635599.jpg

Episode ID: 1800152
URL: https://www.tvmaze.com/episodes/1800152/westworld-3x08-crisis-theory
Name: Crisis Theory
Season: 3
Number: 8
Type: regular
Airdate: 2020-05-03
Airtime: 21:00
Runtime: 75
Average Rating: 7.7
Summary: Time to face the music. Dolores' true intentions are revealed; Bernard confronts a ghost from his past; Maeve is conflicted; Serac's voice is dominant; Caleb's role is revealed; and William faces an unexpected villain.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/254/635189.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/254/635189.jpg

Episode ID: 2326389
URL: https://www.tvmaze.com/episodes/2326389/westworld-4x01-the-auguries
Name: The Auguries
Season: 4
Number: 1
Type: regular
Airdate: 2022-06-26
Airtime: 21:00
Runtime: 55
Average Rating: 7.1
Summary: Hello again. Don't worry about a thing. It's all in your head.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/414/1035413.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/414/1035413.jpg

Episode ID: 2326655
URL: https://www.tvmaze.com/episodes/2326655/westworld-4x02-well-enough-alone
Name: Well Enough Alone
Season: 4
Number: 2
Type: regular
Airdate: 2022-07-03
Airtime: 21:00
Runtime: 55
Average Rating: 7.4
Summary: I heard a fly buzz when I died.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/414/1036909.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/414/1036909.jpg

Episode ID: 2326656
URL: https://www.tvmaze.com/episodes/2326656/westworld-4x03-annees-folles
Name: Années Folles
Season: 4
Number: 3
Type: regular
Airdate: 2022-07-10
Airtime: 21:00
Runtime: 55
Average Rating: 7.6
Summary: You can never go back again. But if you do, bring a shovel.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/415/1038520.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/415/1038520.jpg

Episode ID: 2326657
URL: https://www.tvmaze.com/episodes/2326657/westworld-4x04-generation-loss
Name: Generation Loss
Season: 4
Number: 4
Type: regular
Airdate: 2022-07-17
Airtime: 21:00
Runtime: 51
Average Rating: 7.7
Summary: Should auld acquaintance be forgot and days of auld lang syne?
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/415/1039531.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/415/1039531.jpg

Episode ID: 2326658
URL: https://www.tvmaze.com/episodes/2326658/westworld-4x05-zhuangzi
Name: Zhuangzi
Season: 4
Number: 5
Type: regular
Airdate: 2022-07-24
Airtime: 21:00
Runtime: 60
Average Rating: 7.8
Summary: God is bored.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/416/1042460.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/416/1042460.jpg

Episode ID: 2326659
URL: https://www.tvmaze.com/episodes/2326659/westworld-4x06-fidelity
Name: Fidelity
Season: 4
Number: 6
Type: regular
Airdate: 2022-07-31
Airtime: 21:00
Runtime: 60
Average Rating: 7.5
Summary: To thine own selves be true.
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/417/1044302.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/417/1044302.jpg

Episode ID: 2326660
URL: https://www.tvmaze.com/episodes/2326660/westworld-4x07-metanoia
Name: Metanoia
Season: 4
Number: 7
Type: regular
Airdate: 2022-08-07
Airtime: 21:00
Runtime: 60
Average Rating: 7.7
Summary: You want to have a drink at a time like this?
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/418/1045645.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/418/1045645.jpg

Episode ID: 2326661
URL: https://www.tvmaze.com/episodes/2326661/westworld-4x08-que-sera-sera
Name: Que Será, Será
Season: 4
Number: 8
Type: regular
Airdate: 2022-08-14
Airtime: 21:00
Runtime: 60
Average Rating: 7.5
Summary: Like what I've done with the place? (I just cranked it to expert level.)
Medium Image Link: https://static.tvmaze.com/uploads/images/medium_landscape/418/1046925.jpg
Original Image Link: https://static.tvmaze.com/uploads/images/original_untouched/418/1046925.jpg

**Question 6 -**

Using the data from Question 3, write code to analyze the data and answer the following questions Note 1.

Draw plots to demonstrate the analysis for the following questions for better visualizations.

2. Write code comments wherever required for code understanding

Insights to be drawn -

● Get all Pokemons whose spawn rate is less than 5%

● Get all Pokemons that have less than 4 weaknesses

● Get all Pokemons that have no multipliers at all

● Get all Pokemons that do not have more than 2 evolutions

● Get all Pokemons whose spawn time is less than 300 seconds.

**Note -** spawn time format is "05:32”, so assume “minute: second” format and perform the analysis.

● Get all Pokemon who have more than two types of capabilities

In [75]:
import pandas as pd
import numpy as np
import ast

In [76]:
df1 = pd.read_csv("Output.csv")

In [77]:
df1

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","['Ice', 'Dragon', 'Fairy']","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"['Ice', 'Dragon', 'Fairy']","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"['Ice', 'Rock', 'Dragon', 'Fairy']",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN

In [78]:
# Get all Pokemons that do not have more than 2 evolutions

df = df1.copy()

In [79]:
df["next_evolution"].dropna(inplace=True)

In [80]:
df["Evloutions_2"] = df["next_evolution"].dropna().apply(lambda x: ast.literal_eval(x)).apply(lambda x : len(x)) < 2

In [81]:
df.loc[df["Evloutions_2"] == True]["name"]

1         Ivysaur
4      Charmeleon
7       Wartortle
10        Metapod
13         Kakuna
16      Pidgeotto
18        Rattata
20        Spearow
22          Ekans
24        Pikachu
26      Sandshrew
29       Nidorina
32       Nidorino
34       Clefairy
36         Vulpix
38     Jigglypuff
40          Zubat
43          Gloom
45          Paras
47        Venonat
49        Diglett
51         Meowth
53        Psyduck
55         Mankey
57      Growlithe
60      Poliwhirl
63        Kadabra
66        Machoke
69     Weepinbell
71      Tentacool
74       Graveler
76         Ponyta
78       Slowpoke
80      Magnemite
83          Doduo
85           Seel
87         Grimer
89       Shellder
92        Haunter
95        Drowzee
97         Krabby
99        Voltorb
101     Exeggcute
103        Cubone
108       Koffing
110       Rhyhorn
115        Horsea
117       Goldeen
119        Staryu
128      Magikarp
137       Omanyte
139        Kabuto
147     Dragonair
Name: name, dtype: object

In [82]:
df1

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","['Ice', 'Dragon', 'Fairy']","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"['Ice', 'Dragon', 'Fairy']","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"['Ice', 'Rock', 'Dragon', 'Fairy']",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN

In [83]:
# Get all Pokemons whose spawn time is less than 300 seconds
df = df1.copy()

In [84]:
df["spawn_time_less_then_300"] = df["spawn_time"].dropna().apply(lambda x: (int(x.split(":")[0]) * 60) +(int(x.split(":")[1]))) < 300

In [85]:
df.loc[df["spawn_time_less_then_300"] == True]["name"]

6       Squirtle
8      Blastoise
10       Metapod
12        Weedle
13        Kakuna
         ...
127       Tauros
129     Gyarados
134      Jolteon
136      Porygon
139       Kabuto
Name: name, Length: 75, dtype: object

In [86]:
# Get all Pokemon who have more than two types of capabilities
df = df1.copy()

In [87]:
df["type"] = df["type"].apply(lambda x : ast.literal_eval(x))

In [88]:
df[df["type"].apply(lambda x : len(x) > 2)]["name"]
#There are no pokemon more than two types of capabilities

Series([], Name: name, dtype: object)

**Question 7 -**

Using the data from Question 4, write code to analyze the data and answer the following questions Note -

Draw plots to demonstrate the analysis for the following questions for better visualizations

Write code comments wherever required for code understanding

Insights to be drawn -

● Get all the Earth meteorites that fell before the year 2000

● Get all the earth meteorites co-ordinates who fell before the year 1970

● Assuming that the mass of the earth meteorites was in kg, get all those whose mass was more than 10000kg

**Ans:**

In [95]:
import numpy as np
import pandas as pd

In [96]:
df = pd.read_csv("Output.csv")

In [97]:
df.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

In [98]:
df.shape

(151, 17)

In [104]:
# Get all the Earth meteorites that fell before the year 2000

df["only_year"] = df["year"].apply(lambda x : str(x).split("T")[0].split("-")[0])
df["before_2000"] = df["only_year"].astype(float) < 2000
df.loc[df["before_2000"] == True]["name"]

KeyError: 'year'

In [100]:
# Get all the earth meteorites co-ordinates who fell before the year 1970
import ast
df["year_1970"] = df["only_year"].astype(float) < 1970
coordinates = df.loc[df["year_1970"] == True]["geolocation"].dropna().apply(lambda x : ast.literal_eval(x))
coordinates

KeyError: 'only_year'